import turtle
flag = turtle.Turtle()

def yellowtriangle():
    flag.color('gold')
    flag.begin_fill()
    flag.right(45)
    flag.forward(100)
    flag.right(90)
    flag.forward(100)
    flag.right(135)
    flag.forward(123)
    flag.color('gold')
    flag.end_fill()

def blackTriangle():
    flag.begin_fill()
    flag.color('black')
    flag.right(135)
    flag.forward(73)
    flag.right(90)
    flag.forward(73)
    flag.right(135)
    flag.forward(160)
    flag.color('black')
    flag.end_fill()

def greenArea():
    flag.begin_fill()
    flag.color('green')
    flag.right(90)
    flag.forward(40)
    flag.right(45)
    flag.forward(100)
    flag.left(45)
    flag.forward(300)
    flag.right(90)
    flag.forward(80)
    flag.right(90)
    flag.forward(300)
    flag.left(45)
    flag.forward(100)
    flag.right(45)
    flag.forward(40)
    flag.right(90)
    flag.forward(41)
    flag.right(45)
    flag.forward(100)
    flag.left(90)
    flag.forward(100)
    flag.right(45)
    flag.forward(40)
    flag.right(90)
    flag.forward(55)
    flag.color('green')
    flag.end_fill()


def redArea():
    flag.begin_fill()
    flag.color('red')
    flag.right(45)
    flag.forward(90)
    flag.left(45)
    flag.forward(291)
    flag.left(90)
    flag.forward(64)
    flag.left(90)
    flag.forward(410)
    flag.end_fill()
    flag.color('black')
    flag.left(90)
    flag.forward(223)


def blueArea():
    flag.begin_fill()
    flag.color('blue')
    flag.left(90)
    flag.forward(410)
    flag.left(90)
    flag.forward(63)
    flag.left(90)
    flag.forward(292)
    flag.left(45)
    flag.forward(89)
    flag.color('blue')
    flag.end_fill()

def borderLine():
    flag.color('black')
    flag.pensize(5)
    flag.right(45)
    flag.forward(55)
    flag.right(90)
    flag.forward(223)
    flag.right(90)
    flag.forward(411)
    flag.right(90)
    flag.forward(223)
    flag.right(90)
    flag.forward(355)

yellowtriangle()
blackTriangle()
greenArea()
redArea()
blueArea()
borderLine()